
name: Sync To Notion

on: [push, ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository.
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
         python-version: '3.x'

      - name: Install Dependencies
        run: |
            python3 --version
            python3 -m pip install --upgrade pip
            pip3 install requests
            pip3 install python-slugify
            pip3 install bibtexparser~=1.0

      - name: Sync to notion
        run: python sync.py
        env:
          NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}
          DATABASE_IDENTIFIER: ${{secrets.DATABASE_IDENTIFIER}}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: true
